xkcd:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: service-account
      project: skip-comics
      dataset: xkcd_marts
      threads: 4
      timeout_seconds: 300
      location: northamerica-northeast2
      retries: 1
      keyfile: /Users/aadeshmehra/Desktop/Skip/skip-comics-9b8c28f81a6b.json